function T = getBehaviorVariableName()
high_analysis = {'conv_or_not','converge_angle','detect_wrong','focusAngle','focusDistance','focusPoints','lea',...
    'left_eye_angle','lep','rea','rep','right_eye_angle'}';
leftright_eyes_to_param_angle_dist = {'left_eye_to_param_angle','right_eye_to_param_angle',...
    'left_eye_to_param_angle_visible','right_eye_to_param_angle_visible','param_lefteye_dist','param_righteye_dist'}';
tail_swing = {'left_tail_swing','left_tailswingNum','right_tail_swing','right_tailswingNum','sum_curv'}';
saccade = {'left_end','left_saccade','left_saccade_length','left_start','right_end','right_saccade',...
    'right_saccade_length','right_start','saccadeIdx','saccadeLength','saccadeNum','saccadeRate'}';
low_video_analysis_result = {'amp_all','no_param','param_head_angle_all','param_head_dist_all','param_pos_all'}';
var1 = [high_analysis;leftright_eyes_to_param_angle_dist;tail_swing;saccade;low_video_analysis_result];
var2 = {repmat({'high_analysis'},length(high_analysis),1);...
        repmat({'leftright_eyes_to_param_angle_dist'},length(leftright_eyes_to_param_angle_dist),1);...
        repmat({'tail_swing'},length(tail_swing),1);...
        repmat({'saccade'},length(saccade),1);...
        repmat({'low_video_analysis_result'},length(low_video_analysis_result),1)};
 var2 = cat(1,var2{:});
 T = table(var1,var2,'VariableNames',{'behavior_variables','filename'});
end

